### ISSUE TITLE
[PackageTool.ps1] Conversion from JSON failed with error: Unterminated string.

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/StoreBroker#197]
There's an error running `Update-ApplicationSubmission -ReplacePackages` regarding notes for certification.

```
##[error]ConvertFrom-Json : Conversion from JSON failed with error: Unterminated string. Expected delimiter: ". Path 'appSubmission.notesForCertification', line 1, position 2059.
At D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker\PackageTool.ps1:3276 char:22
```

I am not making any custom package setup; just a clone of previous submission and uploading new packages with the `-ReplacePackages` flag.

## Script

Here's my Powershell script, running in a GitHub Action on a windows machine. Disregard any envVars you dont recognize, they're set earlier on the VM. 

If you want to see the rest of it, [it is public here MediaFileManager CD.yaml](https://github.com/LanceMcCarthy/MediaFileManager/blob/main/.github/workflows/cd.yml).

```
$uploadPackage = "D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\StoreUploadPackages\PackageProject_" + $env:UWP_VERSION + "_" + $env:UwpBundlePlatform + "_bundle.appxupload"
$username = $env:PartnerCenterClientId
$password = ConvertTo-SecureString $env:PartnerCenterClientSecret -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential ($username, $password)

# install StoreBroker
Set-ExecutionPolicy RemoteSigned -Force
git clone https://github.com/Microsoft/StoreBroker.git 'D:\a\MediaFileManager\MediaFileManager\broker\'
Import-Module -Force 'D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker'

# Authenticating with DevCenter
Set-StoreBrokerAuthentication -TenantId $env:PartnerCenterTenantId -Credential $cred

# Generating PDP
$pdpFolderPath = [System.Environment]::GetFolderPath('Desktop')
$pdpFileName = 'Pdp.xml' 
D:\a\MediaFileManager\MediaFileManager\broker\\Extensions\ConvertFrom-ExistingSubmission.ps1 -AppId $env:PartnerCenterStoreId -Release $env:UWP_VERSION -PdpFileName $pdpFileName -OutPath $pdpFolderPath

# Generating SBConfig file
$brokerConfigFilePath = Join-Path -Path ([System.Environment]::GetFolderPath('Desktop')) -ChildPath 'SBConfig.json'
New-StoreBrokerConfigFile -AppId $env:PartnerCenterStoreId -Path $brokerConfigFilePath

# Generate submission Data package
$submissionDataFilePath = Join-Path -Path ([System.Environment]::GetFolderPath('Desktop')) -ChildPath 'submission.json'
New-SubmissionPackage -ConfigPath (Join-Path -Path ([System.Environment]::GetFolderPath('Desktop')) -ChildPath 'SBConfig.json') -PDPRootPath ([System.Environment]::GetFolderPath('Desktop')) -PDPInclude 'Pdp.xml' -ImagesRootPath 'D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\Images' -AppxPath $uploadPackage -OutPath $pdpFolderPath -OutName $submissionDataFilePath

# submitting app
Update-ApplicationSubmission -ReplacePackages -AppId $env:PartnerCenterStoreId -SubmissionDataPath $submissionDataFilePath -PackagePath $uploadPackage -AutoCommit -Force

```

## Output

Here is the output of the run.  To keep it short, I removed the duplicate "I'm busy" updates. 

```
Cloning into 'D:\a\MediaFileManager\MediaFileManager\broker'...

|  Elapsed: 2 second(s) [Getting access token]
DONE - Operation took 2 second(s) [Getting access token]

/  Elapsed: 2 second(s) [Getting data for AppId: 9PD3JFK7W5MB]
DONE - Operation took 2 second(s) [Getting data for AppId: 9PD3JFK7W5MB]
2020-08-11 22:34:07 : runneradmin : Telemetry is currently enabled.  It can be disabled by setting "$global:SBDisableTelemetry = $true". Refer to USAGE.md#telemetry for more information.


-  Elapsed: 4 second(s) [Retrieving nuget package: Microsoft.Bcl.Async]
DONE - Operation took 4 second(s) [Retrieving nuget package: Microsoft.Bcl.Async]
2020-08-11 22:34:13 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\e229bc7e-692a-44fd-8ba5-82b48e7b62d7\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir


\  Elapsed: 2 second(s) [Retrieving nuget package: Microsoft.Diagnostics.Tracing.EventSource.Redist]
DONE - Operation took 2 second(s) [Retrieving nuget package: Microsoft.Diagnostics.Tracing.EventSource.Redist]
2020-08-11 22:34:15 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\e229bc7e-692a-44fd-8ba5-82b48e7b62d7\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.24\lib\net35\Microsoft.Diagnostics.Tracing.EventSource.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir

-  Elapsed: 2 second(s) [Retrieving nuget package: Microsoft.ApplicationInsights]
DONE - Operation took 2 second(s) [Retrieving nuget package: Microsoft.ApplicationInsights]
2020-08-11 22:34:18 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\e229bc7e-692a-44fd-8ba5-82b48e7b62d7\Microsoft.ApplicationInsights.2.0.1\lib\net45\Microsoft.ApplicationInsights.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir

/  Elapsed: 14 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
DONE - Operation took 14 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
2020-08-11 22:34:36 : runneradmin : PDP's have been created here: C:\Users\runneradmin\Desktop
2020-08-11 22:34:36 : runneradmin : You now need to find all of your assets and place them here: <ImagesRootPath>\2020.811.75.0\<langcode>\...
  where <ImagesRootPath> is the path defined in your config file,
  and <langcode> is the same langcode for the directory of the PDP file referencing those assets.
2020-08-11 22:34:36 : runneradmin : Every language that has a PDP references the following assets:
	MFM1.png
	MFM2.png
	MFM3.png


/  Elapsed: 1 second(s) [Getting data for AppId: 9PD3JFK7W5MB]
DONE - Operation took 2 second(s) [Getting data for AppId: 9PD3JFK7W5MB]

/  Elapsed: 6 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
DONE - Operation took 6 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
Write-Error: D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker\PackageTool.ps1:3725
Line |
3725 |          Write-Log -Exception $_ -Level Error
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 2020-08-11 22:34:48 : runneradmin :  ConvertFrom-Json:
     | D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker\PackageTool.ps1:3276 Line |
     | 3276 |      return ($lines | ConvertFrom-Json)      |                     
     | ~~~~~~~~~~~~~~~~      | Conversion from JSON failed with error: Unterminated string.
     | Expected delimiter: ". Path      | 'appSubmission.notesForCertification', line 1, position
     | 2059. 

##[error]ConvertFrom-Json : Conversion from JSON failed with error: Unterminated string. Expected delimiter: ". Path 'appSubmission.notesForCertification', line 1, position 2059.
At D:\a\MediaFileManager\MediaFileManager\broker\StoreBroker\PackageTool.ps1:3276 char:22
+     return ($lines | ConvertFrom-Json)
+                      ~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
+ FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

However, if you would rather see the entire step's output, it is also public here. [Media File Manager - Run 204743631 - Fail](https://github.com/LanceMcCarthy/MediaFileManager/runs/204743631?check_suite_focus=true). 

Be sure to expand the arrows:
![image](https://user-images.githubusercontent.com/3520532/89957380-3fb51280-dc05-11ea-8405-00ee43513e82.png)

**Comment by HowardWolosky** [comment]
Thanks for the report, @LanceMcCarthy.

Would you be willing to share out the config file that was generated at `$brokerConfigFilePath`?  The issue is with the `notesForCertification` that was injected into there, and so I'd like to understand what's going on there.

As an aside, you can completely skip the "Generating PDP" step.  Just don't include the `PDPRootPath` parameter for `New-SubmissionPackage`.  Since you're just doing package updates, there's no need to include any of the metadata.  The metadata is only useful when you're actually trying to update it.

**Comment by HowardWolosky** [comment]
Note for maintainers...relevant code for inspection:

https://github.com/microsoft/StoreBroker/blob/0fbb6b9a702cf0edf52e8f5ef6d920fb859fc954/StoreBroker/PackageTool.ps1#L363-L365


https://github.com/microsoft/StoreBroker/blob/0fbb6b9a702cf0edf52e8f5ef6d920fb859fc954/StoreBroker/Helpers.ps1#L359-L372

**Comment by HowardWolosky** [comment]
It's not clear to me why this isn't calling `ConvertTo-Json` on the result of `Get-EscapedJsonValue` (or instead of calling that entirely).

**Comment by LanceMcCarthy** [comment]
Thanks @HowardWolosky 

I made the suggested changes and do not generate a PDP, but the failure still occurs. See https://github.com/LanceMcCarthy/MediaFileManager/runs/980649893?check_suite_focus=true

In that same run, I did attempt to output the SBconfig.json contents so I could copy/paste it, but I'm not sure it is even reaching that step because I'm not seeing the output. I will try to upload the file to a blob instead.

### Metadata

You're right that I dont have any changes to the metadata in this current iteration, but I plan on building it in because that repo is intended as a "gold standard" for dev community to reference for when they want to see a real-world GitHub Action for deploying a WPF/UWP app to both side-load distributions.

The step prior to the StoreBroker is my own custom GH Action that uploads the `.appinstaller` (and associated packages) to Azure Storage blob. The Store Broker step is the next phase that distributes to the Store (I'll add a flights branch when this works).

### Side Note - Building a new Broker

I am also trying to understand exactly how the API works and what it expects. I'm about 80% done with developing a TypeScript version of the Store Broker that is on npm. Here are the tasks https://github.com/LanceMcCarthy/PartnerCenterBroker/blob/main/src/index.ts 

I have studied the API docs and understand how complicated the payloads can get (the number of nested objects gets gnarly at times https://github.com/LanceMcCarthy/PartnerCenterBroker/blob/main/src/interfaces.ts) so I like the idea of cloning a previous submission and have done that here https://github.com/LanceMcCarthy/PartnerCenterBroker/blob/36901851ace5126d562ed619a6f3c2446831aa85/src/helpers.ts#L25-L47 .

I aim to provide developers with options, no matter what their environment is (at least until PS Core works 100%)

**Comment by HowardWolosky** [comment]
> I made the suggested changes and do not generate a PDP, but the failure still occurs. See https://github.com/LanceMcCarthy/MediaFileManager/runs/980649893?check_suite_focus=true

That's what I would have expected.  That suggestion wasn't to fix the problem, I was simply trying to simplify your script; as you indicated below however, that goes against the goal you were trying to achieve.

> I am also trying to understand exactly how the API works and what it expects. I'm about 80% done with developing a TypeScript version of the Store Broker that is on npm. Here are the tasks https://github.com/LanceMcCarthy/PartnerCenterBroker/blob/main/src/index.ts

There is an [Azure DevOps task](https://github.com/microsoft/windows-dev-center-vsts-extension/tree/master/tasks/store-flight) written in TypeScript that you could look at for reference (or use).

Something for you to consider:  As you might have noticed with this project, there has been minimal activity on the `master` (v1) branch.  The same can't be said of [StoreBroker v2](https://github.com/microsoft/StoreBroker/tree/v2).  StoreBroker v2 is built on top of the next version of the Windows Submission API (v2) which is _substantially_ different than v1, and intended to eventually replace it.  Unfortunately, v2 isn't publicly available yet, and we still don't know what that timeframe would be for its public release.  StoreBroker v2 has been in-use internally now for over 1.5 years, and there's a new version of the Azure DevOps task that is built on top of StoreBroker v2, but that too is only available internally until such time as the new API is made widely available publicly.

**Comment by LanceMcCarthy** [comment]
> That's what I would have expected. That suggestion wasn't to fix the problem, I was simply trying to simplify your script; as you indicated below however, that goes against the goal you were trying to achieve.

Understood, I was just sharing the end result. Thank you for the suggestion as it saves another possible point of failure.

> There is an [Azure DevOps task](https://github.com/microsoft/windows-dev-center-vsts-extension/tree/master/tasks/store-flight) written in TypeScript that you could look at for reference (or use).

Thank you! Although it seems I should not put too much effort into using the v1 endpoints, but if v2 endpoints aren't public yet my options are limited and might as well keep moving forward with it. I can then do a v2 of my package later.


> Something for you to consider: As you might have noticed with this project, there has been minimal activity on the `master` (v1) branch. The same can't be said of [StoreBroker v2](https://github.com/microsoft/StoreBroker/tree/v2). StoreBroker v2 is built on top of the next version of the Windows Submission API (v2) which is _substantially_ different than v1, and intended to eventually replace it. Unfortunately, v2 isn't publicly available yet, and we still don't know what that timeframe would be for its public release. StoreBroker v2 has been in-use internally now for over 1.5 years, and there's a new version of the Azure DevOps task that is built on top of StoreBroker v2, but that too is only available internally until such time as the new API is made widely available publicly.

In my initial research, I did find [the Partner Center APIs](https://docs.microsoft.com/en-us/partner-center/develop/partner-center-rest-api-reference) which heavily use the MS Graph, but do not see any endpoints for App submission :(  This is why my current efforts are still using `manage.devcenter.microsoft.com/v1/` instead

Is it going to be `manage.devcenter.microsoft.com/v2/` or is it going to use `partnercenter.microsoft.com/v1` endpoints?

NDA Help

Although it doesn't sound like you need the testing for v2 of the submission API, but if you do, we can use my MVP NDA for my private Actions 😉 (I would help write day1 blog (similar to my [Windows 10 on ARM: Day-One Developer Experience](https://dvlup.com/2018/03/08/windows-10-on-arm-day-one-developer-experience/) post). I am also under several other TAP programs and have pre-approved clearance for future TAPs/NDAs.

This would not only help me, but I can also have working examples for the community ready-to-go.

**Comment by LanceMcCarthy** [comment]
@HowardWolosky Okay, I tried making this as simple and straightforward as possible by using all full strings where possible and broke out the steps to different stages to catch where it is failing

The Store Broker now seems to hang when trying to generate the SBConfig file (for 26 minutes until the VM quits)

```
************************* GETS STUCK HERE *******************************
# ---- Create config file  
New-StoreBrokerConfigFile -AppId $env:PartnerCenterStoreId -Path 'D:\a\MediaFileManager\MediaFileManager\SBTemp\SBConfig.json'
```



Here are the relevant steps, you can see the offender in Part 2

```yml
 # ************ PART 1  ************ # 
- name: Install Store Broker (SB)
  uses: Amadevus/pwsh-script@v1
  id: install-store-broker
  with:
    script: |
      # ---- Install StoreBroker
      Set-ExecutionPolicy RemoteSigned -Force
      git clone https://github.com/Microsoft/StoreBroker.git 'D:\a\MediaFileManager\MediaFileManager\SBGitRoot\'

# ************ PART 2 ************ #
- name: Authenticate SB and Generate SBConfig.json
  uses: Amadevus/pwsh-script@v1
  id: authenticate-store-brokwer
  with:
    script: |
      $username = $env:PartnerCenterClientId
      $password = ConvertTo-SecureString $env:PartnerCenterClientSecret -AsPlainText -Force
      $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
      Import-Module -Force 'D:\a\MediaFileManager\MediaFileManager\SBGitRoot\StoreBroker'

      # ---- Authenticating with Service Principal Credentials
      Set-StoreBrokerAuthentication -TenantId $env:PartnerCenterTenantId -Credential $cred
      
      # ---- Making a new directory for Store Broker generated files
      New-Item -Path 'D:\a\MediaFileManager\MediaFileManager\SBTemp' -ItemType Directory

******** GETS STUCK HERE (for 26 minutes) ****************
      # ---- Create config file  
      New-StoreBrokerConfigFile -AppId $env:PartnerCenterStoreId -Path 'D:\a\MediaFileManager\MediaFileManager\SBTemp\SBConfig.json'


# ************ PART 3 (debug step to upload the sbconfig.json file to my blob) ************
- name: Uploading SBconfig.json to Azure Blob (temp)
  id: blob-upload-sbconfig
  uses: LanceMcCarthy/Action-AzureBlobUpload@v1.3
  with:
    connection_string: ${{ secrets.AZURE_DVLUP_BLOB_CONNECTION_STRING }}
    container_name: general-app-files
    source_folder: D:\a\MediaFileManager\MediaFileManager\SBTemp\
    destination_folder: SBTemp

# ************ PART 4 do the actual submission ************
- name: Store Broker (Upload the Store build to Microsoft Partner Center)
  uses: Amadevus/pwsh-script@v1
  id: store-broker-submit-app
  with:
    script: |
       $uploadPackage = "D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\StoreUploadPackages\PackageProject_" + 
$env:UWP_VERSION + "_" + $env:UwpBundlePlatform + "_bundle.appxupload"
        $username = $env:PartnerCenterClientId
        $password = ConvertTo-SecureString $env:PartnerCenterClientSecret -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ($username, $password)
          
        Import-Module -Force 'D:\a\MediaFileManager\MediaFileManager\SBGitRoot\StoreBroker'
          
          # ---- Authenticating with Service Principal Credentials
        Set-StoreBrokerAuthentication -TenantId $env:PartnerCenterTenantId -Credential $cred
    
        # ---- Create submissionPackage
        New-SubmissionPackage -ConfigPath 'D:\a\MediaFileManager\MediaFileManager\SBTemp\submission.json' -ImagesRootPath 'D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\Images' -AppxPath $uploadPackage -OutPath 'D:\a\MediaFileManager\MediaFileManager\SBTemp\' -OutName 'submission.json'
      
        # ---- Submitting app, we only want to close last submission and just update package
        Update-ApplicationSubmission -ReplacePackages -AppId $env:PartnerCenterStoreId -SubmissionDataPath 'D:\a\MediaFileManager\MediaFileManager\SBTemp\submission.json' -PackagePath $uploadPackage -AutoCommit -Force
```


## Output

Here is the out put from step 2 (with repeated lines removed)

```
- Elapsed: 0 second(s) [Getting access token]
**** REDACTED ****
DONE - Operation took 2 second(s) [Getting access token]

Elapsed: 0 second(s) [Getting data for AppId: 9PD3JFK7W5MB]
**** REDACTED ****
DONE - Operation took 3 second(s) [Getting data for AppId: 9PD3JFK7W5MB]
2020-08-13 22:19:15 : runneradmin : Telemetry is currently enabled.  It can be disabled by setting "$global:SBDisableTelemetry = $true". Refer to USAGE.md#telemetry for more information.


-  Elapsed: 0 second(s) [Retrieving nuget package: Microsoft.Bcl.Async]
**** REDACTED ****
DONE - Operation took 4 second(s) [Retrieving nuget package: Microsoft.Bcl.Async]
2020-08-13 22:19:21 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\ecf83896-abd9-4c21-b5eb-ea9e170df8ff\Microsoft.Bcl.Async.1.0.168\lib\net40\Microsoft.Threading.Tasks.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\SBGitRoot\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir
  

|  Elapsed: 0 second(s) [Retrieving nuget package: Microsoft.Diagnostics.Tracing.EventSource.Redist]
**** REDACTED ****
DONE - Operation took 2 second(s) [Retrieving nuget package: Microsoft.Diagnostics.Tracing.EventSource.Redist]
2020-08-13 22:19:23 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\ecf83896-abd9-4c21-b5eb-ea9e170df8ff\Microsoft.Diagnostics.Tracing.EventSource.Redist.1.1.24\lib\net35\Microsoft.Diagnostics.Tracing.EventSource.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\SBGitRoot\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir
  

|  Elapsed: 2 second(s) [Retrieving nuget package: Microsoft.ApplicationInsights]
**** REDACTED ****
DONE - Operation took 2 second(s) [Retrieving nuget package: Microsoft.ApplicationInsights]
2020-08-13 22:19:26 : runneradmin : To avoid this download delay in the future, copy the following file:
  [C:\Users\RUNNER~1\AppData\Local\Temp\ecf83896-abd9-4c21-b5eb-ea9e170df8ff\Microsoft.ApplicationInsights.2.0.1\lib\net45\Microsoft.ApplicationInsights.dll]
either to:
  [D:\a\MediaFileManager\MediaFileManager\SBGitRoot\StoreBroker]
or to:
  a directory of your choosing, and save that directory path to $SBAlternateAssemblyDir
  
 -  Elapsed: 0 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
**** REDACTED ****
DONE - Operation took 9 second(s) [Getting data for AppId: 9PD3JFK7W5MB SubmissionId: 1152921505688863279]
```

Here's the run if you want to see the whole thing https://github.com/LanceMcCarthy/MediaFileManager/runs/982539639?check_suite_focus=true
